### ISSUE TITLE
What is DataFacet()?

### ISSUE THREAD

**Issue by uponai** [fortesp/xsd2xml#2]
Can You please make a detailed description about what is this DataFacet()?

**Comment by fortesp** [comment]
Its been a while since i work on this. When i have time i will. DataFacet was a class which you could override the facets implementation. So for each type, generate a specific data.

**Comment by fortesp** [comment]
I've made changes; improvements; etc.

**Comment by uponai** [comment]
Sorry for the late answer! I will try it very soon! Thanks!
